// Constantes para el frontend

export const BOOK_GENRES = [
  "Ficción",
  "No ficción",
  "Ciencia ficción",
  "Fantasía",
  "Romance",
  "Misterio",
  "Terror",
  "Historia",
  "Biografía",
  "Ciencia",
  "Tecnología",
  "Negocios",
  "Autoayuda",
  "Salud",
  "Cocina",
  "Viajes",
  "Arte",
  "Música",
  "Poesía",
  "Drama",
  "Filosofía",
  "Psicología",
  "Religión",
  "Política",
  "Deportes",
  "Humor",
  "Ensayos",
  "Educación",
  "Referencia",
  "Juvenil",
  "Aventura",
  "Crimen",
  "General",
];

export const READING_STATUSES = {
  WANT_TO_READ: "por_leer",
  READING: "leyendo",
  READ: "leido",
  ABANDONED: "abandonado",
};
