-- Script para cargar todas las ubicaciones de Chile
-- Este script incluye todas las regiones y comunas de Chile

-- Primero, limpiar la tabla existente
DELETE FROM "LocationBook";

-- Insertar todas las regiones y comunas de Chile
INSERT INTO "LocationBook" (location_id, region, comuna) VALUES
-- Región de Arica y Parinacota
(1, 'Arica y Parinacota', 'Arica'),
(2, 'Arica y Parinacota', 'Camarones'),
(3, 'Arica y Parinacota', 'Putre'),
(4, 'Arica y Parinacota', 'General Lagos'),

-- Región de Tarapacá
(5, 'Tarapacá', 'Iquique'),
(6, 'Tarapacá', 'Alto Hospicio'),
(7, 'Tarapacá', 'Pozo Almonte'),
(8, 'Tarapacá', 'Camiña'),
(9, 'Tarapacá', 'Colchane'),
(10, 'Tarapacá', 'Huara'),
(11, 'Tarapacá', 'Pica'),

-- Región de Antofagasta
(12, 'Antofagasta', 'Antofagasta'),
(13, 'Antofagasta', 'Mejillones'),
(14, 'Antofagasta', 'Sierra Gorda'),
(15, 'Antofagasta', 'Taltal'),
(16, 'Antofagasta', 'Calama'),
(17, 'Antofagasta', 'Ollagüe'),
(18, 'Antofagasta', 'San Pedro de Atacama'),
(19, 'Antofagasta', 'Tocopilla'),
(20, 'Antofagasta', 'María Elena'),

-- Región de Atacama
(21, 'Atacama', 'Copiapó'),
(22, 'Atacama', 'Caldera'),
(23, 'Atacama', 'Tierra Amarilla'),
(24, 'Atacama', 'Chañaral'),
(25, 'Atacama', 'Diego de Almagro'),
(26, 'Atacama', 'Vallenar'),
(27, 'Atacama', 'Alto del Carmen'),
(28, 'Atacama', 'Freirina'),
(29, 'Atacama', 'Huasco'),

-- Región de Coquimbo
(30, 'Coquimbo', 'La Serena'),
(31, 'Coquimbo', 'Coquimbo'),
(32, 'Coquimbo', 'Andacollo'),
(33, 'Coquimbo', 'La Higuera'),
(34, 'Coquimbo', 'Paiguano'),
(35, 'Coquimbo', 'Vicuña'),
(36, 'Coquimbo', 'Illapel'),
(37, 'Coquimbo', 'Canela'),
(38, 'Coquimbo', 'Los Vilos'),
(39, 'Coquimbo', 'Salamanca'),
(40, 'Coquimbo', 'Ovalle'),
(41, 'Coquimbo', 'Combarbalá'),
(42, 'Coquimbo', 'Monte Patria'),
(43, 'Coquimbo', 'Punitaqui'),
(44, 'Coquimbo', 'Río Hurtado'),

-- Región de Valparaíso
(45, 'Valparaíso', 'Valparaíso'),
(46, 'Valparaíso', 'Casablanca'),
(47, 'Valparaíso', 'Concón'),
(48, 'Valparaíso', 'Juan Fernández'),
(49, 'Valparaíso', 'Puchuncaví'),
(50, 'Valparaíso', 'Quintero'),
(51, 'Valparaíso', 'Viña del Mar'),
(52, 'Valparaíso', 'Isla de Pascua'),
(53, 'Valparaíso', 'Los Andes'),
(54, 'Valparaíso', 'Calle Larga'),
(55, 'Valparaíso', 'Rinconada'),
(56, 'Valparaíso', 'San Esteban'),
(57, 'Valparaíso', 'La Ligua'),
(58, 'Valparaíso', 'Cabildo'),
(59, 'Valparaíso', 'Papudo'),
(60, 'Valparaíso', 'Petorca'),
(61, 'Valparaíso', 'Zapallar'),
(62, 'Valparaíso', 'Quillota'),
(63, 'Valparaíso', 'Calera'),
(64, 'Valparaíso', 'Hijuelas'),
(65, 'Valparaíso', 'La Cruz'),
(66, 'Valparaíso', 'Nogales'),
(67, 'Valparaíso', 'San Antonio'),
(68, 'Valparaíso', 'Algarrobo'),
(69, 'Valparaíso', 'Cartagena'),
(70, 'Valparaíso', 'El Quisco'),
(71, 'Valparaíso', 'El Tabo'),
(72, 'Valparaíso', 'Santo Domingo'),
(73, 'Valparaíso', 'San Felipe'),
(74, 'Valparaíso', 'Catemu'),
(75, 'Valparaíso', 'Llaillay'),
(76, 'Valparaíso', 'Panquehue'),
(77, 'Valparaíso', 'Putaendo'),
(78, 'Valparaíso', 'Santa María'),
(79, 'Valparaíso', 'Quilpué'),
(80, 'Valparaíso', 'Limache'),
(81, 'Valparaíso', 'Olmué'),
(82, 'Valparaíso', 'Villa Alemana'),

-- Región Metropolitana de Santiago
(83, 'Metropolitana de Santiago', 'Santiago'),
(84, 'Metropolitana de Santiago', 'Cerrillos'),
(85, 'Metropolitana de Santiago', 'Cerro Navia'),
(86, 'Metropolitana de Santiago', 'Conchalí'),
(87, 'Metropolitana de Santiago', 'El Bosque'),
(88, 'Metropolitana de Santiago', 'Estación Central'),
(89, 'Metropolitana de Santiago', 'Huechuraba'),
(90, 'Metropolitana de Santiago', 'Independencia'),
(91, 'Metropolitana de Santiago', 'La Cisterna'),
(92, 'Metropolitana de Santiago', 'La Florida'),
(93, 'Metropolitana de Santiago', 'La Granja'),
(94, 'Metropolitana de Santiago', 'La Pintana'),
(95, 'Metropolitana de Santiago', 'La Reina'),
(96, 'Metropolitana de Santiago', 'Las Condes'),
(97, 'Metropolitana de Santiago', 'Lo Barnechea'),
(98, 'Metropolitana de Santiago', 'Lo Espejo'),
(99, 'Metropolitana de Santiago', 'Lo Prado'),
(100, 'Metropolitana de Santiago', 'Macul'),
(101, 'Metropolitana de Santiago', 'Maipú'),
(102, 'Metropolitana de Santiago', 'Ñuñoa'),
(103, 'Metropolitana de Santiago', 'Pedro Aguirre Cerda'),
(104, 'Metropolitana de Santiago', 'Peñalolén'),
(105, 'Metropolitana de Santiago', 'Providencia'),
(106, 'Metropolitana de Santiago', 'Pudahuel'),
(107, 'Metropolitana de Santiago', 'Quilicura'),
(108, 'Metropolitana de Santiago', 'Quinta Normal'),
(109, 'Metropolitana de Santiago', 'Recoleta'),
(110, 'Metropolitana de Santiago', 'Renca'),
(111, 'Metropolitana de Santiago', 'San Joaquín'),
(112, 'Metropolitana de Santiago', 'San Miguel'),
(113, 'Metropolitana de Santiago', 'San Ramón'),
(114, 'Metropolitana de Santiago', 'Vitacura'),
(115, 'Metropolitana de Santiago', 'Puente Alto'),
(116, 'Metropolitana de Santiago', 'Pirque'),
(117, 'Metropolitana de Santiago', 'San José de Maipo'),
(118, 'Metropolitana de Santiago', 'Colina'),
(119, 'Metropolitana de Santiago', 'Lampa'),
(120, 'Metropolitana de Santiago', 'Tiltil'),
(121, 'Metropolitana de Santiago', 'San Bernardo'),
(122, 'Metropolitana de Santiago', 'Buin'),
(123, 'Metropolitana de Santiago', 'Calera de Tango'),
(124, 'Metropolitana de Santiago', 'Paine'),
(125, 'Metropolitana de Santiago', 'Melipilla'),
(126, 'Metropolitana de Santiago', 'Alhué'),
(127, 'Metropolitana de Santiago', 'Curacaví'),
(128, 'Metropolitana de Santiago', 'María Pinto'),
(129, 'Metropolitana de Santiago', 'San Pedro'),
(130, 'Metropolitana de Santiago', 'Talagante'),
(131, 'Metropolitana de Santiago', 'El Monte'),
(132, 'Metropolitana de Santiago', 'Isla de Maipo'),
(133, 'Metropolitana de Santiago', 'Padre Hurtado'),
(134, 'Metropolitana de Santiago', 'Peñaflor'),

-- Región del Libertador General Bernardo O'Higgins
(135, 'O\'Higgins', 'Rancagua'),
(136, 'O\'Higgins', 'Codegua'),
(137, 'O\'Higgins', 'Coinco'),
(138, 'O\'Higgins', 'Coltauco'),
(139, 'O\'Higgins', 'Doñihue'),
(140, 'O\'Higgins', 'Graneros'),
(141, 'O\'Higgins', 'Las Cabras'),
(142, 'O\'Higgins', 'Machalí'),
(143, 'O\'Higgins', 'Malloa'),
(144, 'O\'Higgins', 'Mostazal'),
(145, 'O\'Higgins', 'Olivar'),
(146, 'O\'Higgins', 'Peumo'),
(147, 'O\'Higgins', 'Pichidegua'),
(148, 'O\'Higgins', 'Quinta de Tilcoco'),
(149, 'O\'Higgins', 'Rengo'),
(150, 'O\'Higgins', 'Requínoa'),
(151, 'O\'Higgins', 'San Vicente'),
(152, 'O\'Higgins', 'Pichilemu'),
(153, 'O\'Higgins', 'La Estrella'),
(154, 'O\'Higgins', 'Litueche'),
(155, 'O\'Higgins', 'Marchihue'),
(156, 'O\'Higgins', 'Navidad'),
(157, 'O\'Higgins', 'Paredones'),
(158, 'O\'Higgins', 'San Fernando'),
(159, 'O\'Higgins', 'Chépica'),
(160, 'O\'Higgins', 'Chimbarongo'),
(161, 'O\'Higgins', 'Lolol'),
(162, 'O\'Higgins', 'Nancagua'),
(163, 'O\'Higgins', 'Palmilla'),
(164, 'O\'Higgins', 'Peralillo'),
(165, 'O\'Higgins', 'Placilla'),
(166, 'O\'Higgins', 'Pumanque'),
(167, 'O\'Higgins', 'Santa Cruz'),

-- Región del Maule
(168, 'Maule', 'Talca'),
(169, 'Maule', 'Constitución'),
(170, 'Maule', 'Curepto'),
(171, 'Maule', 'Empedrado'),
(172, 'Maule', 'Maule'),
(173, 'Maule', 'Pelarco'),
(174, 'Maule', 'Pencahue'),
(175, 'Maule', 'Río Claro'),
(176, 'Maule', 'San Clemente'),
(177, 'Maule', 'San Rafael'),
(178, 'Maule', 'Cauquenes'),
(179, 'Maule', 'Chanco'),
(180, 'Maule', 'Pelluhue'),
(181, 'Maule', 'Curicó'),
(182, 'Maule', 'Hualañé'),
(183, 'Maule', 'Licantén'),
(184, 'Maule', 'Molina'),
(185, 'Maule', 'Rauco'),
(186, 'Maule', 'Romeral'),
(187, 'Maule', 'Sagrada Familia'),
(188, 'Maule', 'Teno'),
(189, 'Maule', 'Vichuquén'),
(190, 'Maule', 'Linares'),
(191, 'Maule', 'Colbún'),
(192, 'Maule', 'Longaví'),
(193, 'Maule', 'Parral'),
(194, 'Maule', 'Retiro'),
(195, 'Maule', 'San Javier'),
(196, 'Maule', 'Villa Alegre'),
(197, 'Maule', 'Yerbas Buenas'),

-- Región del Ñuble
(198, 'Ñuble', 'Chillán'),
(199, 'Ñuble', 'Bulnes'),
(200, 'Ñuble', 'Cobquecura'),
(201, 'Ñuble', 'Coelemu'),
(202, 'Ñuble', 'Coihueco'),
(203, 'Ñuble', 'Chillán Viejo'),
(204, 'Ñuble', 'El Carmen'),
(205, 'Ñuble', 'Ninhue'),
(206, 'Ñuble', 'Ñiquén'),
(207, 'Ñuble', 'Pemuco'),
(208, 'Ñuble', 'Pinto'),
(209, 'Ñuble', 'Portezuelo'),
(210, 'Ñuble', 'Quillón'),
(211, 'Ñuble', 'Quirihue'),
(212, 'Ñuble', 'Ránquil'),
(213, 'Ñuble', 'San Carlos'),
(214, 'Ñuble', 'San Fabián'),
(215, 'Ñuble', 'San Ignacio'),
(216, 'Ñuble', 'San Nicolás'),
(217, 'Ñuble', 'Treguaco'),
(218, 'Ñuble', 'Yungay'),

-- Región del Biobío
(219, 'Biobío', 'Concepción'),
(220, 'Biobío', 'Coronel'),
(221, 'Biobío', 'Chiguayante'),
(222, 'Biobío', 'Florida'),
(223, 'Biobío', 'Hualqui'),
(224, 'Biobío', 'Lota'),
(225, 'Biobío', 'Penco'),
(226, 'Biobío', 'San Pedro de la Paz'),
(227, 'Biobío', 'Santa Juana'),
(228, 'Biobío', 'Talcahuano'),
(229, 'Biobío', 'Tomé'),
(230, 'Biobío', 'Hualpén'),
(231, 'Biobío', 'Lebu'),
(232, 'Biobío', 'Arauco'),
(233, 'Biobío', 'Cañete'),
(234, 'Biobío', 'Contulmo'),
(235, 'Biobío', 'Curanilahue'),
(236, 'Biobío', 'Los Álamos'),
(237, 'Biobío', 'Tirúa'),
(238, 'Biobío', 'Los Ángeles'),
(239, 'Biobío', 'Antuco'),
(240, 'Biobío', 'Cabrero'),
(241, 'Biobío', 'Laja'),
(242, 'Biobío', 'Mulchén'),
(243, 'Biobío', 'Nacimiento'),
(244, 'Biobío', 'Negrete'),
(245, 'Biobío', 'Quilaco'),
(246, 'Biobío', 'Quilleco'),
(247, 'Biobío', 'San Rosendo'),
(248, 'Biobío', 'Santa Bárbara'),
(249, 'Biobío', 'Tucapel'),
(250, 'Biobío', 'Yumbel'),
(251, 'Biobío', 'Alto Biobío'),

-- Región de La Araucanía
(252, 'La Araucanía', 'Temuco'),
(253, 'La Araucanía', 'Carahue'),
(254, 'La Araucanía', 'Cunco'),
(255, 'La Araucanía', 'Curarrehue'),
(256, 'La Araucanía', 'Freire'),
(257, 'La Araucanía', 'Galvarino'),
(258, 'La Araucanía', 'Gorbea'),
(259, 'La Araucanía', 'Lautaro'),
(260, 'La Araucanía', 'Loncoche'),
(261, 'La Araucanía', 'Melipeuco'),
(262, 'La Araucanía', 'Nueva Imperial'),
(263, 'La Araucanía', 'Padre Las Casas'),
(264, 'La Araucanía', 'Perquenco'),
(265, 'La Araucanía', 'Pitrufquén'),
(266, 'La Araucanía', 'Pucón'),
(267, 'La Araucanía', 'Saavedra'),
(268, 'La Araucanía', 'Teodoro Schmidt'),
(269, 'La Araucanía', 'Toltén'),
(270, 'La Araucanía', 'Vilcún'),
(271, 'La Araucanía', 'Villarrica'),
(272, 'La Araucanía', 'Cholchol'),
(273, 'La Araucanía', 'Angol'),
(274, 'La Araucanía', 'Collipulli'),
(275, 'La Araucanía', 'Curacautín'),
(276, 'La Araucanía', 'Ercilla'),
(277, 'La Araucanía', 'Lonquimay'),
(278, 'La Araucanía', 'Los Sauces'),
(279, 'La Araucanía', 'Lumaco'),
(280, 'La Araucanía', 'Purén'),
(281, 'La Araucanía', 'Renaico'),
(282, 'La Araucanía', 'Traiguén'),
(283, 'La Araucanía', 'Victoria'),

-- Región de Los Ríos
(284, 'Los Ríos', 'Valdivia'),
(285, 'Los Ríos', 'Corral'),
(286, 'Los Ríos', 'Lanco'),
(287, 'Los Ríos', 'Los Lagos'),
(288, 'Los Ríos', 'Máfil'),
(289, 'Los Ríos', 'Mariquina'),
(290, 'Los Ríos', 'Paillaco'),
(291, 'Los Ríos', 'Panguipulli'),
(292, 'Los Ríos', 'La Unión'),
(293, 'Los Ríos', 'Futrono'),
(294, 'Los Ríos', 'Lago Ranco'),
(295, 'Los Ríos', 'Río Bueno'),

-- Región de Los Lagos
(296, 'Los Lagos', 'Puerto Montt'),
(297, 'Los Lagos', 'Calbuco'),
(298, 'Los Lagos', 'Cochamó'),
(299, 'Los Lagos', 'Fresia'),
(300, 'Los Lagos', 'Frutillar'),
(301, 'Los Lagos', 'Los Muermos'),
(302, 'Los Lagos', 'Llanquihue'),
(303, 'Los Lagos', 'Maullín'),
(304, 'Los Lagos', 'Puerto Varas'),
(305, 'Los Lagos', 'Castro'),
(306, 'Los Lagos', 'Ancud'),
(307, 'Los Lagos', 'Chonchi'),
(308, 'Los Lagos', 'Curaco de Vélez'),
(309, 'Los Lagos', 'Dalcahue'),
(310, 'Los Lagos', 'Puqueldón'),
(311, 'Los Lagos', 'Queilén'),
(312, 'Los Lagos', 'Quellón'),
(313, 'Los Lagos', 'Quemchi'),
(314, 'Los Lagos', 'Quinchao'),
(315, 'Los Lagos', 'Osorno'),
(316, 'Los Lagos', 'Puerto Octay'),
(317, 'Los Lagos', 'Purranque'),
(318, 'Los Lagos', 'Puyehue'),
(319, 'Los Lagos', 'Río Negro'),
(320, 'Los Lagos', 'San Juan de la Costa'),
(321, 'Los Lagos', 'San Pablo'),
(322, 'Los Lagos', 'Chaitén'),
(323, 'Los Lagos', 'Futaleufú'),
(324, 'Los Lagos', 'Hualaihué'),
(325, 'Los Lagos', 'Palena'),

-- Región de Aysén del General Carlos Ibáñez del Campo
(326, 'Aysén', 'Coyhaique'),
(327, 'Aysén', 'Lago Verde'),
(328, 'Aysén', 'Aysén'),
(329, 'Aysén', 'Cisnes'),
(330, 'Aysén', 'Guaitecas'),
(331, 'Aysén', 'Cochrane'),
(332, 'Aysén', 'O\'Higgins'),
(333, 'Aysén', 'Tortel'),
(334, 'Aysén', 'Chile Chico'),
(335, 'Aysén', 'Río Ibáñez'),

-- Región de Magallanes y de la Antártica Chilena
(336, 'Magallanes', 'Punta Arenas'),
(337, 'Magallanes', 'Laguna Blanca'),
(338, 'Magallanes', 'Río Verde'),
(339, 'Magallanes', 'San Gregorio'),
(340, 'Magallanes', 'Cabo de Hornos'),
(341, 'Magallanes', 'Antártica'),
(342, 'Magallanes', 'Porvenir'),
(343, 'Magallanes', 'Primavera'),
(344, 'Magallanes', 'Timaukel'),
(345, 'Magallanes', 'Natales'),
(346, 'Magallanes', 'Torres del Paine');

-- Verificar que se insertaron correctamente
SELECT COUNT(*) as total_locations FROM "LocationBook";
SELECT region, COUNT(*) as comunas FROM "LocationBook" GROUP BY region ORDER BY region; 